### ISSUE TITLE
Break out Docker into its own Repository - 5 pt

### ISSUE THREAD

**Issue by rossbernet** [geotrellis/geopyspark-netcdf#4]
- This will expose what the "module" system is
    - What is the pattern for adding more JARS/BINs 
- Pin docker build to specific SHA of GPS/GN
- Auto publish docker container on CI
- Break out GeoPySpark from friends
    - I want to update GPS without triggering wider updates
- Clear hook for local development
    - Mounting GPS/GN/JARS as source directories and relying on python auto reload

**Comment by jamesmcclain** [comment]
The docker build now exists [here](https://github.com/geodocker/geodocker-jupyter-geopyspark/)
